services:
    api:
        image: pollutionpatrol.api
        build:
            context: .
            dockerfile: src/API/PollutionPatrol.API/Dockerfile
            
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
                
        ports:
            - 8080:8080
    
    seq:
        image: datalust/seq:latest
        container_name: seq
        
        environment:
            - ACCEPT_EULA=Y
                
        ports:
            - 5341:5341
            - 8081:80
            
